apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mc
  name: mc
spec:
  containers:
  - name: mc
    env:
    - name: MC_HOST_minio
      value: "http://minio:minio123@minio-service.minio:9000"
    - name: MC_URL
      value: "http://minio-service.minio:9000"
    command: ["sleep","3600"]
    image: minio/mc:RELEASE.2022-06-11T21-10-36Z
  restartPolicy: Never

## old release RELEASE.2021-04-22T17-40-00Z
## new  release  RELEASE.2022-06-11T21-10-36Z